services:
  pg:
    image: postgres:17
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ja-x-icu"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
