FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g corepack@latest
RUN corepack enable
RUN apt-get update \
  && apt-get install -y libssl-dev \
  && apt clean \
  && rm -rf /var/lib/apt/lists/*
COPY . /app
COPY ./.env.example.prod /app/.env
WORKDIR /app

FROM base AS prod-deps
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm install --frozen-lockfile

FROM base AS build
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm install --frozen-lockfile
RUN pnpm build

FROM base AS next
COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=build /app/src/data-accesses/infra/prisma/generated /app/src/data-accesses/infra/prisma/generated
COPY --from=build /app/.next /app/.next
EXPOSE 3000
CMD [ "pnpm", "start" ]
