import './globals.css';

import { myUserDetailData } from '@/data-access/entities/user/MyUserDetailData';
import { resetToken } from '@/server-actions/auth/resetToken';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await resetToken({}, new FormData());
  const myUser = await myUserDetailData.findOne();

  return (
    <html lang='en' className='h-full'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <div className='h-full flex flex-col'>
          <div className='h-8 m-4 flex justify-between items-center'>
            <div />
            {myUser && <div>{myUser.name}</div>}
          </div>
          <div className='h-full'>{children}</div>
        </div>
      </body>
    </html>
  );
}
